# version: "3.9"
services:
  db:
    image: mysql:8
    container_name: dash_db
    environment:
      MYSQL_DATABASE: dashboard
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--mysql-native-password=ON" ]
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    build: ./backend
    container_name: dash_api
    environment:
      - DB_URL=mysql://root:123456@db:3306/dashboard?charset=utf8mb4
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
  # frontend:
  #   build: ./frontend
  #   container_name: dash_web
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:8000
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"

volumes:
  db_data:
